### ISSUE TITLE
Graphviz generation error with 2.38.0

### ISSUE THREAD

**Issue by harryhaaren** [fundamental/stoat#16]
Hi,

I'm encountering an error on using the --graph-view switch, in a simple one file `main.c` test using:
```
stoat -r . --graph-view graph.png
```

Error is as follows:
```
Error #1:
main
##The Deduction Chain:
##The Contradiction Reasons:
 - printf : Assumed Unsafe

Total of 1 error(s)
Total Functions:   3
Total Realtime:    1
Total NonRealtime: 1
Parsing './main.bc'...
/usr/share/stoat/graph.rb:51:in `to_graph': uninitialized constant GraphRender::GraphViz (NameError)
	from /usr/bin/stoat:312:in `<main>'
```

I'm on Arch linux with Graphviz current, and just ran `gem install graphviz`.. perhaps there's a mismatch there? I'm no Ruby coder - so I'm not sure. Cheers, -Harry

**Comment by fundamental** [comment]
For some historic reason there was a graphviz gem which was overtaken by the 'ruby-graphviz' gem and both of them end up requiring the same file so it looks like a more complicated error than it is.
This is further complicated by some distros which seem to package 'ruby-graphviz' as the default gem for 'graphviz'.
So, to fix this "gem uninstall graphviz && gem install ruby-graphviz".

Additionally I've added some warnings within stoat itself to display the needed corrections for future users who grab the wrong gem.

**Comment by harryhaaren** [comment]
Confirmed fixed - working fine now. Super-fast fix! Cheers
