### ISSUE TITLE
Demangled names can exceed YAML's 1024 character key limit

### ISSUE THREAD

**Issue by dsacre** [fundamental/stoat#19]
YAML (and Ruby's YAML parser) has a key length limit of 1024 characters. I hit this limit running stoat on mididings:

    Parsing 'src/python_module.o.bc'...
    /usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (stoat_vtable.txt): could not find expected ':' while scanning a simple key at line 37 column 1 (Psych::SyntaxError)
        from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
        from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
        from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
        from /usr/lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
        from /usr/lib/ruby/1.9.1/psych.rb:297:in `open'
        from /usr/lib/ruby/1.9.1/psych.rb:297:in `load_file'
        from /usr/local/share/stoat/load-callgraph.rb:52:in `block in load_callgraph'
        from /usr/local/share/stoat/load-callgraph.rb:26:in `each'
        from /usr/local/share/stoat/load-callgraph.rb:26:in `load_callgraph'
        from /usr/local/bin/stoat:262:in `<main>'

The key is nothing fancy really, just a function taking a `map<string, vector<string>>`, wrapped with Boost.Python...:

    boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (mididings::backend::BackendBase::*)(std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&), boost::python::default_call_policies, boost::mpl::vector4<void, mididings::backend::BackendBase&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > > const&> > >

My current workaround is to simply change ExtractVtables::handleVtable() to shorten names to 1024 characters (the function in question is not relevant to realtime-issues anyway). Is there a better solution, other than changing stoat's vtable file format?

**Comment by fundamental** [comment]
Oh goodness boost, that's a long type signature.

I'd side with just truncating the signatures as the YAML files do make it easier to look at the output manually if need be. To be 100% correct, yeah this would require either a change of the format s.t. the names aren't used directly and they're stored in another table, but I'm hesitant to go for that. I'm pretty sure one of the iterations used that approach (perhaps sfpv as I built tables to llvm::clang::someOtherNamespace::Function pointers rather than using the stringified names in parts of the code) and debugging issues with that was a giant pain.

**Comment by dsacre** [comment]
In boost's defense, `map<string, vector<string>>` alone is around 250 characters when fully spelled out. The function actually takes two of those, and each argument appears (only) twice in the type signature... :)

Does this look ok to you?
dsacre@de217823c621b262f99963f69a86746eca1811ed

I take it the shortened names only affect what would appear in the output/graph, and stoat uses mangled names for everything else?

**Comment by fundamental** [comment]
That might be sufficient in practice as llvm does replace lengthy templated type names with shorter versions, but it might make sense to just limit some of the other printfs to this limit (when they're getting used as keys).

Shortened names should only show up in the graphviz renderings, though they're also used in pattern matching for the white/black lists. They can't be used at the YAML file level as collisions happen too easily.

**Comment by dsacre** [comment]
Here's a more complete patch. Is this what you had in mind?
dsacre@e9b527a5dc855eb31760acb894f4a8667749d3e6

**Comment by fundamental** [comment]
Yeah that looks right. I'll try to merge that in this afternoon.

**Comment by fundamental** [comment]
Merged. I've also added you to the contributor list on github, so you should have commit access as well. thanks :+1:
