### ISSUE TITLE
Error in suppressions mechanism

### ISSUE THREAD

**Issue by tobiasherzke** [fundamental/stoat#27]
A suppression file
```
a ==> A
b ==> B
```
will not only suppress calls from a to A and from b to B, 

but will also suppress calls from a to B and from b to A

in the current implementation.

**Comment by fundamental** [comment]
Creating a minimal test case (see the last commit) does not appear to exhibit this behavior on my system. Could you perhaps provide an example of a a/b/A/B set of pairs for which this bug seems to exist with?

**Comment by tobiasherzke** [comment]
You are right. My own example does not reproduce this as I try now. 
As I was trying this out stoat to learn about suppression, I guess I forgot to recreate the .bc file after making a change to the source and before rerunning stoat analysis.
Thanks for looking into it and sorry for the noise.
