### ISSUE TITLE
Ruby error in create_alias_map

### ISSUE THREAD

**Issue by drobilla** [fundamental/stoat#38]
MacOS 10.12.6 with Ruby 2.5.0

```
/usr/local/share/stoat/load-callgraph.rb:117:in `block in create_alias_map': undefined method `each' for #<String:0x007feafb873118> (NoMethodError)
	from /usr/local/share/stoat/load-callgraph.rb:116:in `each'
	from /usr/local/share/stoat/load-callgraph.rb:116:in `create_alias_map'
	from /usr/local/share/stoat/load-callgraph.rb:55:in `block in load_callgraph'
	from /usr/local/share/stoat/load-callgraph.rb:26:in `each'
	from /usr/local/share/stoat/load-callgraph.rb:26:in `load_callgraph'
	from /usr/local/bin/stoat:262:in `<main>'
```

**Comment by fundamental** [comment]
This error means with high likelyhood there was a problem in the LLVM pass. Could you paste the contents of "stoat_class.txt"? Since stoat crashed it should not have removed the file.

**Comment by drobilla** [comment]
Indeed it was, mismatched versions or something.  Sorry for the noise (though something that looks like a parse error and not an awful lot like a Ruby version incompatibility would be nice).
